"""User model: removing user_free column

Revision ID: f6c43c2fb6f4
Revises: 
Create Date: 2023-11-03 18:51:23.270306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c43c2fb6f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    op.drop_table('instructor')
    op.drop_table('students')
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_column('user_free')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_free', sa.BOOLEAN(), autoincrement=False, nullable=False))

    op.create_table('students',
    sa.Column('student_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('studet_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('student_id', name='students_pkey')
    )
    op.create_table('instructor',
    sa.Column('instructor_uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('instructor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('instructor_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('instructor_middle_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('instructor_last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('instructor_full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('instructor_uid', name='instructor_pkey'),
    sa.UniqueConstraint('instructor_id', name='instructor_instructor_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('courses',
    sa.Column('course_uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('course_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('course_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('course_rank', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('course_instrcutor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_instrcutor_id'], ['instructor.instructor_uid'], name='courses_course_instrcutor_id_fkey'),
    sa.PrimaryKeyConstraint('course_uid', name='courses_pkey'),
    sa.UniqueConstraint('course_instrcutor_id', name='courses_course_instrcutor_id_key')
    )
    # ### end Alembic commands ###
