"""Adding address model and some modifications in client model

Revision ID: 6fcd21456e20
Revises: cd45e4e39d14
Create Date: 2024-01-03 20:54:13.781204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fcd21456e20'
down_revision = 'cd45e4e39d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_adress_model',
    sa.Column('adress_uid', sa.Uuid(), nullable=False),
    sa.Column('address_client_id', sa.Uuid(), nullable=False),
    sa.Column('client_state', sa.String(), nullable=False),
    sa.Column('client_city', sa.String(), nullable=False),
    sa.Column('client_postal_code', sa.String(), nullable=False),
    sa.Column('client_delivery_address', sa.String(), nullable=False),
    sa.Column('client_created_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['address_client_id'], ['client_model.client_uid'], ),
    sa.PrimaryKeyConstraint('adress_uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_adress_model')
    # ### end Alembic commands ###
