"""First migration to DB

Revision ID: cd45e4e39d14
Revises: 
Create Date: 2023-11-10 16:12:54.929875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd45e4e39d14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_model',
    sa.Column('item_uid', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_price', sa.Float(), nullable=False),
    sa.Column('item_availability', sa.Boolean(), nullable=False),
    sa.Column('item_created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('item_uid'),
    sa.UniqueConstraint('item_id')
    )
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('item_uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('item_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('item_availability', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('item_uid', name='items_pkey'),
    sa.UniqueConstraint('item_id', name='items_item_id_key')
    )
    op.drop_table('items_model')
    # ### end Alembic commands ###
